package me.tabacowang.mvvmarch

import com.jakewharton.threetenabp.AndroidThreeTen
import dagger.android.AndroidInjector
import dagger.android.DaggerApplication
import me.tabacowang.mvvmarch.di.DaggerAppComponent
import me.tabacowang.mvvmarch.util.CrashlyticsTree
import timber.log.Timber

class MainApplication : DaggerApplication() {

    override fun onCreate() {
        // ThreeTenBP for times and dates, called before super to be available for objects
        AndroidThreeTen.init(this)

        super.onCreate()

        if (BuildConfig.DEBUG) {
            Timber.plant(Timber.DebugTree())
        } else {
            Timber.plant(CrashlyticsTree())
        }
    }

    /**
     * Tell Dagger which [AndroidInjector] to use - in our case
     * [me.tabacowang.mvvmarch.di.AppComponent]. `DaggerAppComponent`
     * is a class generated by Dagger based on the `AppComponent` class.
     */
    override fun applicationInjector(): AndroidInjector<out DaggerApplication> {
        return DaggerAppComponent.builder().create(this)
    }
}